// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfKEpCpVrEgvIigHRUhq4_pdmlk0cbsWs',
    appId: '1:762442170539:web:78f46c63df697a97d5b7ee',
    messagingSenderId: '762442170539',
    projectId: 'objremover',
    authDomain: 'objremover.firebaseapp.com',
    storageBucket: 'objremover.appspot.com',
    measurementId: 'G-F0F0HK6C1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKTwQRndpEYLSrR4LKZPOzR_pSgOLP58w',
    appId: '1:762442170539:android:5c11cb0354e9e3b3d5b7ee',
    messagingSenderId: '762442170539',
    projectId: 'objremover',
    storageBucket: 'objremover.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA15tVjT--_MQBYM02r2y4dEQZXwdf97Hg',
    appId: '1:762442170539:ios:32ba92166c142ee9d5b7ee',
    messagingSenderId: '762442170539',
    projectId: 'objremover',
    storageBucket: 'objremover.appspot.com',
    iosBundleId: 'com.example.objectRemoverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA15tVjT--_MQBYM02r2y4dEQZXwdf97Hg',
    appId: '1:762442170539:ios:109f07204ea65cc1d5b7ee',
    messagingSenderId: '762442170539',
    projectId: 'objremover',
    storageBucket: 'objremover.appspot.com',
    iosBundleId: 'com.example.objectRemoverApp.RunnerTests',
  );
}
